name: datathon
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.7
  - pip
  - pip:
      - transformers[torch]==4.10.2
      - huggingface-hub==0.0.17
      - datasets==1.12.1
      - scikit-learn==0.24.2
      - fastai==2.5.2
  - pytorch=1.9.0
  - torchvision=0.10.0
  - torchaudio=0.9.0
  - cudatoolkit=11.1
  - jupyterlab=3.1.12
  - ipykernel=6.4.1
  - ipywidgets=7.6.5